apiVersion: v1
kind: Pod
metadata:
  name: devops-001
  labels:
    name: devops-001
    type: backend
    app: app-service
    project-name: devopsproject
spec:
  containers:
    - name: devops-001
      image: ferhataydin/devops-001
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 9090