apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-001
spec:
  replicas: 5
  selector:
    matchLabels:
      app: devops-001
  template:
    metadata:
      labels:
        app: devops-001
    spec:
      containers:
        - name: devops-001
          image: ferhataydin/devops-001:v001
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 9090
